name = "maf-machine-dev"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[triggers]
crons = ["0 3 * * *"]

routes = [
  { pattern = "maf-dev.marliin.com/*", zone_name = "marliin.com" }
]

[assets]
directory = "../app/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[kv_namespaces]]
binding = "MAF_TOKENS"
id = "eadad87860a24db297e36d810cccfa94"

[[kv_namespaces]]
binding = "MAF_ACTIVITIES"
id = "6b88824b06b548899d517d70739faa23"

[[kv_namespaces]]
binding = "MAF_SETTINGS"
id = "d0d1c96a7b834c0490728d705f57c533"

[[kv_namespaces]]
binding = "MAF_GAME"
id = "ad1c22de0f0e40df909bc311bd2c1b19"

[vars]
DEV_MODE = "true"
DEV_ATHLETE_ID = "9127290"
